/// \file include/nauths/mml/algos/common.hh
/// \file include/nauths/mml/algos/common.hxx
/// \file include/nauths/mml/algos/contains.hh
/// \file include/nauths/mml/algos/contains.hxx
/// \file include/nauths/mml/algos.hh
/// \file include/nauths/mml/algos/overlaps.hh
/// \file include/nauths/mml/algos/overlaps.hxx
/// \file include/nauths/mml/constants.hh
/// \file include/nauths/mml/io.hh
/// \file include/nauths/mml/io/ostream.hh
/// \file include/nauths/mml/io/ostream.hxx
/// \file include/nauths/mml/lib/dual_iterator.hh
/// \file include/nauths/mml/lib/misc.hh
/// \file include/nauths/mml/lib/operators.hh
/// \file include/nauths/mml/lib/real.hh
/// \file include/nauths/mml/lib/template.hh
/// \file include/nauths/mml/lib/utils.hh
/// \file include/nauths/mml/mml.hh
/// \file include/nauths/mml/shapes/circle.hh
/// \file include/nauths/mml/shapes/circle.hxx
/// \file include/nauths/mml/shapes/empty.hh
/// \file include/nauths/mml/shapes/hash.hh
/// \file include/nauths/mml/shapes/hash.hxx
/// \file include/nauths/mml/shapes.hh
/// \file include/nauths/mml/shapes/line.hh
/// \file include/nauths/mml/shapes/line.hxx
/// \file include/nauths/mml/shapes/point.hh
/// \file include/nauths/mml/shapes/point.hxx
/// \file include/nauths/mml/shapes/polygon.hh
/// \file include/nauths/mml/shapes/polygon.hxx
/// \file include/nauths/mml/shapes/rect.hh
/// \file include/nauths/mml/shapes/rect.hxx
/// \file include/nauths/mml/shapes/shape_base.hh
/// \file include/nauths/mml/shapes/shape_base.hxx
/// \file include/nauths/mml/shapes/shape.hh
/// \file include/nauths/mml/shapes/shape.hxx
/// \file include/nauths/mml/shapes/shape_macros.hh
/// \file include/nauths/mml/shapes/shape_type.hh
/// \file include/nauths/mml/shapes/shape_union.hh
/// \file include/nauths/mml/shapes/shape_utils.hh
/// \file include/nauths/mml/tools/grid.hh
/// \file include/nauths/mml/tools/grid.hxx
/// \file include/nauths/mml/tools.hh
/// \file include/nauths/mml/tools/perlin.hh
/// \file include/nauths/mml/tools/perlin.hxx
/// \file include/nauths/mml/tools/tiling.hh
/// \file include/nauths/mml/tools/tiling.hxx
/// \file include/nauths/mml/types.hh
